// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx4WUOWJfopFiqpqjIdu0omCd6UvWZRzg',
    appId: '1:335803116123:web:6319c85526765393b56d7e',
    messagingSenderId: '335803116123',
    projectId: 'easyexpress-e7856',
    authDomain: 'easyexpress-e7856.firebaseapp.com',
    storageBucket: 'easyexpress-e7856.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7NK-rQ5cJSRm2Vgpt3W0fOE1tpTE2-3o',
    appId: '1:335803116123:android:0237335b504db05fb56d7e',
    messagingSenderId: '335803116123',
    projectId: 'easyexpress-e7856',
    storageBucket: 'easyexpress-e7856.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu4NDxS4VYYZfXOYaKaTJzP0O-CMrMW8A',
    appId: '1:335803116123:ios:f2408735dea66edeb56d7e',
    messagingSenderId: '335803116123',
    projectId: 'easyexpress-e7856',
    storageBucket: 'easyexpress-e7856.firebasestorage.app',
    androidClientId: '335803116123-dsvmsccf41pbgv3s2375cn5truf08a6a.apps.googleusercontent.com',
    iosClientId: '335803116123-rtk1mdo1r4n3j0tn1ukb79r1fpddeivp.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyexpres',
  );
}
